name: bugrani2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  provider: ^6.0.0 # Add the provider package
  qr_flutter: ^4.0.0 # Add the qr_flutter package
  shared_preferences: ^2.0.0 # Add the shared_preferences package

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/